### ISSUE TITLE
按照教程配置无法完成安装

### ISSUE THREAD

**Issue by xpzouying** [wangchucheng/hugo-eureka#10]
你好，
我按照[教程](https://www.wangchucheng.com/zh/docs/eureka/getting-started/)进行安装，报错。

我的步骤：

1. 初始化项目：

```bash
hugo new site quickstart

cd quickstart

git init .

# 按照教程走
git submodule add https://github.com/wangchucheng/hugo-eureka.git themes/eureka

cp -r themes/eureka/exampleSite/config .

rm config.toml

# 配置后，运行

hugo server
```

报错：

![image](https://user-images.githubusercontent.com/3946563/99907386-87c0f680-2d17-11eb-9437-955045a44ff7.png)

**Comment by wangchucheng** [comment]
请确认你的Hugo版本满足Eureka文档中的要求，目前要求0.74.0以上。祝好！
