### ISSUE TITLE
How can I make an author page the home page?

### ISSUE THREAD

**Issue by ChristianFJung** [wangchucheng/hugo-eureka#11]
It is possible to make the author page the homepage? 

Thank you

**Comment by wangchucheng** [comment]
@ChristianFJung Hi,

Right now, it isn’t. But I am planning a feature that can enable you to use widgets to organize homepage and fully customize homepage.

This feature may take some time but it will definitely come out.

**Comment by wangchucheng** [comment]
See https://www.wangchucheng.com/en/docs/eureka/homepage-configuration/
