### ISSUE TITLE
所有文章都显示 “1分钟阅读时长”，请问是否支持设置

### ISSUE THREAD

**Issue by leonfrer** [wangchucheng/hugo-eureka#111]

**Comment by wangchucheng** [comment]
请详细描述你的问题，以便为你提供更好的帮助。

祝好！

**Comment by leonfrer** [comment]
![image](https://user-images.githubusercontent.com/51883574/120092270-2fdece80-c144-11eb-9d91-03adb722af34.png)
就是这里的阅读时长的设置，谢谢

**Comment by wangchucheng** [comment]
这个是hugo根据你的文章长度自动生成的。如果文章内容变长，阅读时间也会相应变长。

祝好！

**Comment by leonfrer** [comment]
好的，我是看我的文章有几千字也显示1分钟才会有疑问的。。。

**Comment by wangchucheng** [comment]
如果有几千字的话确实不该显示1分钟。时间是使用的hugo的.ReadingTime变量，如果确定是相关错误，可以在hugo中提出issue。
