### ISSUE TITLE
怎样才能让docs目录里面的文档不出现在生成的文档页面左侧的目录里面，但是点击链接又可以找到这个文档呢？

### ISSUE THREAD

**Issue by nodenota** [wangchucheng/hugo-eureka#113]
怎样才能让docs目录里面的文档不出现在生成的文档页面左侧的目录里面，但是点击链接又可以找到这个文档呢？

**Comment by wangchucheng** [comment]
据我所知，hugo好像没有提供这个功能


________________________________
发件人: nodenota ***@***.***>
发送时间: Thursday, June 10, 2021 9:02:49 AM
收件人: wangchucheng/hugo-eureka ***@***.***>
抄送: Subscribed ***@***.***>
主题: [wangchucheng/hugo-eureka] 怎样才能让docs目录里面的文档不出现在生成的文档页面左侧的目录里面，但是点击链接又可以找到这个文档呢？ (#113)


怎样才能让docs目录里面的文档不出现在生成的文档页面左侧的目录里面，但是点击链接又可以找到这个文档呢？

―
