### ISSUE TITLE
Command failed with exit code 255: hugo

### ISSUE THREAD

**Issue by KifoLee** [wangchucheng/hugo-eureka#12]
10:40:08 PM: Error: "/opt/build/repo/themes/hugo-eureka/layouts/partials/doc_layout.html:166:1": parse failed: template: partials/doc_layout.html:166: function "return" not defined
10:40:08 PM: ​
10:40:08 PM: ────────────────────────────────────────────────────────────────
10:40:08 PM:   "build.command" failed                                        
10:40:08 PM: ────────────────────────────────────────────────────────────────
10:40:08 PM: ​
10:40:08 PM:   Error message
10:40:08 PM:   Command failed with exit code 255: hugo
10:40:08 PM: ​
10:40:08 PM:   Error location
10:40:08 PM:   In Build command from Netlify app:
10:40:08 PM:   hugo
10:40:08 PM: ​
10:40:08 PM:   Resolved config

**Comment by KifoLee** [comment]
> @KifoLee Hi,
> 
> Can you tell me your Hugo version and Eureka version? It is easier to help you with these information.

The Hugo version is the latest, 0.78.2. I'm not sure the Eureka version, but I set it through this github today.

**Comment by KifoLee** [comment]
@wangchucheng 
I can run it in R blogdown, but when I deploy it in netlify, I met the issue. I like your theme so much, but I have only few knowledge about web. Could you please solve the problem? Thank you very much.

**Comment by wangchucheng** [comment]
@KifoLee I think this is not an Eureka issue.

You should set an environment variable in netlify to set Hugo version. Because the default version is a relative low one.

Thank you for your appreciation of Eureka!
