### ISSUE TITLE
Ampersand (&) not displaying 

### ISSUE THREAD

**Issue by ecthrwatch** [wangchucheng/hugo-eureka#123]
**Describe the bug**

Ampersand (&) doesn't always display properly and sometimes shows as "&amp;".
Example: I create a post with the word "AT&T" in it. It sometimes shows as "AT&T" and sometimes shows as "AT&amp;T"

**To Reproduce**

Does this issue reproduce with the latest release?

Yes.

1. Create a post with the word "AT&T"
2. Display the post which was just created. For example, go to https://Hugo-eureka-website/posts/att_corporation_post_just_created/ => "AT&T" will be displayed correctly.
3. However, if you visit https://Hugo-eureka-website/posts/ the summary of the "att_corporation_post_just_created" post will display as AT&amp;T which is not the expected behavior.

**Expected behavior**

When listing the summaries of the posts, if one of the summary contains the ampersand logogram (&), it should display as & instead of &amp;

**Environment**

 - Hugo Version: [e.g. v0.83.1]
 - Eureka Version: [e.g. v0.8.0]

**Comment by wangchucheng** [comment]
Thanks, I can reproduce this issue and I think this bug will be fixed in next release!

**Comment by ecthrwatch** [comment]
Thank you!
Also, I've just realized that if a post is tagged with a group of words which contains the ampersand logogram (i.e. &), when we click on it to see all of the related posts with that given tag, we are being redirected to the homepage. Do you want me to open a separate issue for that or will you fix everything in one go?

**Comment by ecthrwatch** [comment]
Here is an example:
https://fr.ecthrwatch.org/chronologie/2015-10-27_reponse_d_eric_andrieu_cabinet_pechenard/
The name of the law firm is "Péchenard & Associés". If I click on the hashtag, I don't see the related posts.

**Comment by wangchucheng** [comment]
I will check this issue first, but according to the current description, this may be a problem with hugo rather than eureka. Let me take a look first ;-)
________________________________
发件人: ECTHRwatch ***@***.***>
发送时间: Tuesday, July 6, 2021 11:21:50 AM
收件人: wangchucheng/hugo-eureka ***@***.***>
抄送: C. Wang ***@***.***>; State change ***@***.***>
主题: Re: [wangchucheng/hugo-eureka] Ampersand (&) not displaying (#123)


Thank you!
Also, I've just realized that if a post is tagged with a group of words which contains the ampersand logogram (i.e. &), when we click on it to see all of the related posts with that given tag, we are being redirected to the homepage. Do you want me to open a separate issue for that or will you fix everything in one go?

―

**Comment by ecthrwatch** [comment]
In addition to that, you will also realize that the language switch doesn't display. I am not certain if it's something wrong I did on my side. (I am new to Hugo)

**Comment by wangchucheng** [comment]
The language switch will show only if this page has different languages options.
________________________________
发件人: ECTHRwatch ***@***.***>
发送时间: Tuesday, July 6, 2021 11:26:06 AM
收件人: wangchucheng/hugo-eureka ***@***.***>
抄送: C. Wang ***@***.***>; State change ***@***.***>
主题: Re: [wangchucheng/hugo-eureka] Ampersand (&) not displaying (#123)


In addition to that, you will also realize that the language switch doesn't display. I am not certain if it's something wrong I did on my side. (I am new to Hugo)

―

**Comment by ecthrwatch** [comment]
I see. So the slug must be identical, otherwise, it won't show the options for the other languages, is that right?

For example, here, we can see the language switch:
https://www.ecthrwatch.org/posts/

But here, we can't:
https://www.ecthrwatch.org/timeline/
(since the translation of "timeline" in French is "chronologie"

**Comment by wangchucheng** [comment]
> So the slug must be identical

Yes, and hugo provides some other ways to achieve this. For reference: https://gohugo.io/content-management/multilingual/#bypassing-default-linking

**Comment by wangchucheng** [comment]
> Also, I've just realized that if a post is tagged with a group of words which contains the ampersand logogram (i.e. &), when we click on it to see all of the related posts with that given tag, we are being redirected to the homepage.

I tested this with `AT&T` and your use case. They both work well ;-)
