### ISSUE TITLE
Param "description" in a post has no effect

### ISSUE THREAD

**Issue by KermanX** [wangchucheng/hugo-eureka#136]
**Describe the bug**

中文: 文章的`description`参数不起作用
English: param `description` in a post has no effect

**To Reproduce**

> Does this issue reproduce with the latest release?
> Yes

**Steps to reproduce the behavior:**
1. add a post like this:
```
---
title: Raychess
description: 全球独一无二的纸上+线上游戏
toc: true
authors: [_Kerman]
tags: []
categories: []
series: []
date: 2021-09-13T13:53:12+08:00
lastmod: 2021-09-13T13:53:12+08:00
featuredVideo:
featuredImage:
draft: false
---

# Repository

## Gitee

<script src='https://gitee.com/UniCoderGroup/raychess/widget_preview' async defer></script>
<div id="osc-gitee-widget-tag"></div>
<style>
.osc_pro_color {color: #4183c4 !important;}
.osc_panel_color {background-color: #dcebf5 !important;}
.osc_background_color {background-color: #ffffff !important;}
.osc_border_color {border-color: #e3e9ed !important;}
.osc_desc_color {color: #666666 !important;}
.osc_link_color * {color: #9b9b9b !important;}
</style>
```
2. After rendering:
![image](https://user-images.githubusercontent.com/63178754/133032649-b0bd035b-8d92-463e-b955-df1eb49edc7d.png)
I can't see the `description`("全球独一无二的纸上+线上游戏") anywhere

**Expected behavior**

Replace 
![image](https://user-images.githubusercontent.com/63178754/133032974-0404bf68-140a-4a83-8f0d-baac5681f29f.png)
with 
![image](https://user-images.githubusercontent.com/63178754/133033063-711fcbe8-1649-4c1d-b3be-fd7cd2def5f9.png)
by 
![image](https://user-images.githubusercontent.com/63178754/133033102-4bcc6d1e-16cb-40ec-9a5f-efdc691aea9b.png)

**Environment**

 - Hugo Version: [Hugo Static Site Generator v0.79.0/extended windows/amd64 BuildDate: unknown]
 - Eureka Version: [v0.8.2]

**Comment by wangchucheng** [comment]
Thanks! This bug has been fixed in 920c3cc.
