### ISSUE TITLE
Header Menu (Eureka Demo, ...) jumping left and right when each menu button is clicked

### ISSUE THREAD

**Issue by natasak** [wangchucheng/hugo-eureka#14]
If you click "About" the whole header jumps to the right, if you click "Posts" the whole header jumps back to the left, ... Maybe the problem is content width.

**Comment by wangchucheng** [comment]
@natasak I will check and fix this issue in the next few days, thank you for your feedback!

**Comment by wangchucheng** [comment]
@natasak  This bug has been fixed in 6638e3a.

You can checkout master to preview it or wait for the next release which may be released in days.

Thank you for your feedback to Eureka!
