### ISSUE TITLE
The blank line after the first paragraph cannot be rendered correctly

### ISSUE THREAD

**Issue by stO-Orz** [wangchucheng/hugo-eureka#16]
Hi. I find sth strange but I don't know whether it is caused by the setting problem or it's a bug.

If the first paragraph of the content had no header, then the blank line after this paragraph will not be rendered correctly, which means that:

- if the second paragraph also had no header, then these two paragraphs will stick to each other without a blank line between them
- if the element after the blank line is `---`, then the horizontal line will be close to the first paragraph than the content after it

For example, if the source code of the markdown is 

```txt
aaa

bbb
```

it will be rendered as

```txt
aaa
bbb
```

instead of

```txt
aaa

bbb
```

I hope that I describe the problem clearly :)

**Comment by wangchucheng** [comment]
@stO-Orz Hi, I think this is a markdown renderer issue.

Hugo uses goldmark as its default markdown renderer since 0.60. And a Hugo theme such as Eureka can not change the render behavior.

Thank you for your feedback of Eureka!

**Comment by stO-Orz** [comment]
All right …… Thanks for your reply :)
