### ISSUE TITLE
希望增加更多配置项以提高可定制化程度

### ISSUE THREAD

**Issue by NaT5uK1** [wangchucheng/hugo-eureka#167]
代码块：
1. 边框样式
2. 配色样式
3. 复制按钮
4. 显示行号

[样式参考](https://raw.githubusercontent.com/kufii/CodeSnap/master/examples/material_operator-mono.png)

除此之外，由于主推hugo module的更新方式，修改样式多有不便，那么是否考虑推出自定义eureka module的方案?（或许这本不该是个问题，fork仓库修改再发布也能办到，但有违使用主题的初衷）

**Comment by wangchucheng** [comment]
代码块的大部分样式可通过修改Hugo的配置解决（https://gohugo.io/content-management/syntax-highlighting/ ），因此不在Eureka处理的范畴内。

> 那么是否考虑推出自定义eureka module的方案?

Hugo提供了覆盖主题特定样式的功能，可见：https://gohugobrasil.netlify.app/themes/customizing/ 需要注意的是，这个是一个**非官方**的网站，请注意甄别其中的内容。
