### ISSUE TITLE
Valine 无法正常使用

### ISSUE THREAD

**Issue by 9201314** [wangchucheng/hugo-eureka#171]
**Describe the bug**

Valine 无法正常使用

**To Reproduce**

最新版的 Hugo 和 Eureka

看了一下网页加载错误，应该是没有将 url 设置为 params.yaml 配置文件中的 server-URLs，还是用的官方已经不支持的默认 URL：https://us.leancloud.cn/1.1/classes/Comment

现在国际版 Valine 的 serverURLs 都必须设置为 https://xxxxxxxx.api.lncldglobal.com 这样的

**Expected behavior**

希望能修改一下 Valine 的配置，把 Valine 的 URL 设置为 params.yaml 里的 serverURLs

**Screenshots**

![报错](https://user-images.githubusercontent.com/45234281/158825327-84007e47-ba02-4091-8aaa-15d3fe2e6715.png)
![params.yaml](https://user-images.githubusercontent.com/45234281/158825475-c68811a2-6ca3-41a8-9c47-9f5e359a1dec.png)

**Environment**

 - Hugo Version: lastest
 - Eureka Version: lastest

**Comment by wangchucheng** [comment]
感谢提出issue！如果使用`server-U-R-Ls`属性的情况下依然会有这个bug吗？

**Comment by 9201314** [comment]
感谢作者，想到了对大写不敏感加了一个横杠，没想到这么不敏感😂
问题解决了，谢谢！
