### ISSUE TITLE
所有 CSS 不要计算对比哈希

### ISSUE THREAD

**Issue by 9201314** [wangchucheng/hugo-eureka#172]
eureka.css 经过 Cloudflare 压缩之后哈希会变，导致被锁无法加载。所以是否可以不要计算对比 CSS 的哈希

**Comment by wangchucheng** [comment]
未来可能会计划添加是否验证sri的配置。

目前css生成时已经经过压缩的，所以可以通过停止再次压缩的方式避免此问题，祝好！

On Mar 17, 2022, at 22:10, 二洲 ***@***.***> wrote:

﻿

eureka.css 经过 Cloudflare 压缩之后哈希会变，导致被锁无法加载。所以是否可以不要计算对比 CSS 的哈希

**Comment by 9201314** [comment]
不压缩 CSS 可以解决问题。但不是很明白为什么 CSS 要校验这个？
