### ISSUE TITLE
social显示不出

### ISSUE THREAD

**Issue by ZYOOO** [wangchucheng/hugo-eureka#178]
**Describe the bug**

在about中对social进行了配置, 但是显示不出来, 不知道是哪里出问题了呢
配置信息如下
social: 
  - icon: github
    iconPack: brands
    url: https://github.com/xxx
  - icon: envelope
    iconPack: solid
    url: xxx@126.com
在font awesome上面查找到的信息如下
 class="fa-solid fa-envelope" 
 class="fa-brands fa-github"
是哪里出错了吗? 期待你的回复, 感谢!!!

**Comment by wangchucheng** [comment]
应该是由于fontawesome5到fontawesome6的不兼容设置导致的。请参考fontawesome5的文档即可，祝好！

**Comment by ZYOOO** [comment]
> 应该是由于fontawesome5到fontawesome6的不兼容设置导致的。请参考fontawesome5的文档即可，祝好！

好的, 谢谢!
