### ISSUE TITLE
Slug added to eureka.min.css for v0.9.1

### ISSUE THREAD

**Issue by ragonneau** [wangchucheng/hugo-eureka#179]
**Describe the bug**

When I generate my website using hugo-eureka v0.9.1, the name of the file `eureka.min.css` includes a slug (e.g., `eureka.min.6a378a...235017.css`). Hence, the file is never reached by the HTML pages.

**To Reproduce**

Does this issue reproduce with the latest release?
This issue occurs with the latest release only.

1. Clone `https://github.com/ragonneau/ragonneau.co.git`.
2. Update the hugo-eureka submodule in `themes/eureka` to v0.9.1.
3. Generate the static pages with `hugo`.

**Expected behavior**

The file should not include slugs.

**Screenshots**

**Environment**

 - Hugo Version: v0.96.0
 - Eureka Version: v0.9.1

**Additional context**

**Comment by wangchucheng** [comment]
My website is also using Eureka 0.9.1 and it is fine. The hash is generated by Hugo and can be handled in Hugo/Eureka. Did you use `eureka.min.css` yourself somewhere else?

**Comment by ragonneau** [comment]
I did not use `eureka.min.css` myself, but I use CI/CD pipelines to generate the website automatically from the sources. What should I do for Hugo/Eureka to handle the problem?

Thank you!

**Comment by wangchucheng** [comment]
Can you share a generated head of html and errors in you CI or console if any?

**Comment by ragonneau** [comment]
The console is as follows.

```
“https://www.ragonneau.co/css/eureka.min.6a378a23360d238dc3ef4df2f5cd718093f02c10c9c7eb2437c29701cd8d389ab6da5d9f21bdd3afa305fd56c1235017.css” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.
“https://www.ragonneau.co/js/eureka.min.a3e627c430c1281e6e0f18283a36c9cd4ddd90b993c45656c2290b897d81d6b0753b8fd02dc595974e0b8afcb4e8e1ea.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.
“https://www.ragonneau.co/js/fontawesome.min.3e9f41040ad856543a87ed70e6bd8756efb3b120939541a9dfabf3ad9cce7bba5a4ee7a353073ed6bbac07507c663fa7.js” is not eligible for integrity checks since it’s neither CORS-enabled nor same-origin.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/styles/solarized-light.min.css. (Reason: CORS request did not succeed). Status code: (null).
The resource from “https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/styles/solarized-light.min.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
Uncaught ReferenceError: getcolorscheme is not defined
    <anonymous> https://ragonneau.co/en/:17
[en:17:637](https://ragonneau.co/en/)
    <anonymous> https://ragonneau.co/en/:17
```
