### ISSUE TITLE
首页Slogan根据不同语言切换

### ISSUE THREAD

**Issue by joey66666** [wangchucheng/hugo-eureka#18]
如果首页Slogan可以根据不同语言设置不同的Slogan就更好了

**Comment by wangchucheng** [comment]
@joey66666 若想实现不同语言属性值不同只需在`languages.toml`文件中指定即可。

例如单独设置英文（假设其为`en`）下的slogan属性，只需在`languages.toml`中的`[en]`中添加如下属性：

```
[en]
    languageCode = "en"
    languageName = "English"
    contentDir = "content/en"
    title = "Tech Mansion"
    [en.params.hero]
        slogan = "test"
```

这是Hugo内置的属性设置方式，可以针对所有属性值。感谢你对Eureka的关注！
