### ISSUE TITLE
网站icon使用外链图片报错

### ISSUE THREAD

**Issue by joey66666** [wangchucheng/hugo-eureka#19]
params.toml中第17行
```
icon = "images/icon.png"
```
这里如果使用外链图片，如
```
icon = "https://raw.githubusercontent.com/joey66666/ImgHost/main/avatar/z.png"
```
会报如下错误
![image](https://user-images.githubusercontent.com/25404074/102566378-64bd1300-411a-11eb-894e-59a2b5356f10.png)

**Comment by wangchucheng** [comment]
@joey66666 为了获得更好的设备兼容性及可能的seo原因，在目前的版本中，需要使用Hugo内置的图像处理功能将icon缩放为不同尺寸（32*32等），所以根据Eureka的[在配置文件中添加图片](https://www.wangchucheng.com/zh/docs/eureka/content-management/#%E5%9C%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%AD%E6%B7%BB%E5%8A%A0%E5%9B%BE%E7%89%87)，icon图片只支持存放于assets文件夹中。

感谢你对Eureka的关注！
