### ISSUE TITLE
不能设置单行代码高亮

### ISSUE THREAD

**Issue by fengguowudi** [wangchucheng/hugo-eureka#191]
在正常的markdown语言中

`任意内容` 应该是代码单行高亮的，但是在此主题中没有效果

**Comment by wangchucheng** [comment]
单行代码应该需要代码高亮，但Hugo生成的html代码中并没有为单行代码设置与多行代码类似的标识符，因此没有被自带的高亮/highlightjs识别。为了与Hugo的默认行为保持一致，因此也没有对Hugo生成的代码进行额外的修改。
