### ISSUE TITLE
Failed to transform "js/fontawesome.js"

### ISSUE THREAD

**Issue by onkoe** [wangchucheng/hugo-eureka#192]
**Describe the bug**

When running Hugo in my project folder, I get the following error: 
```
barrett@mocha ~/D/onkoe.github.io (monolingual) [255]> hugo server
Start building sites …
hugo v0.98.0+extended linux/amd64 BuildDate=unknown
Error: Error building site: JSBUILD: failed to transform "js/fontawesome.js" (application/javascript): The symbol "faEnvelope" has already been declared
Built in 49 ms
barrett@mocha ~/D/onkoe.github.io (monolingual) [255]>
```

**To Reproduce**

Does this issue reproduce with the latest release? Yes, v0.9.1

1. Type a Hugo command such as `hugo server` or just `hugo`
2. Fails to launch anything 

**Expected behavior**
As with previous runs, it should just open the website in my browser. I may have touched something I shouldn't have, but all I did was remove some of the sample content. Have I made a configuration error? 

**Environment**

 - Hugo Version: Hugo v0.98.0+extended linux/amd64 BuildDate=unknown (also occurs on v0.80.0 for Fedora)
 - Eureka Version: v0.9.1

**Additional context**
Already tried clearing /tmp/hugo_cache a few times - doesn't seem to change anything! If it helps, you may see the changes I made from the default repo with [this commit!](https://github.com/onkoe/onkoe.github.io/commit/41661503783457fa10ee993238da62f83fb610da) Thanks for the great project! Until now, this theme has been amazing to use! :)

**Comment by wangchucheng** [comment]
Can you share a repo which has this issue? I think there might be something wrong with the variable declaration but I can not debug it without examples.

**Comment by onkoe** [comment]
> Can you share a repo which has this issue? I think there might be something wrong with the variable declaration but I can not debug it without examples.

I linked a repo in the final paragraph of my issue. If this one doesn't work, or isn't minimal enough, please let me know! :)
