### ISSUE TITLE
hugo v0.99.0 会报错

### ISSUE THREAD

**Issue by 9201314** [wangchucheng/hugo-eureka#193]
用最新版的 v0.99.0 的 hugo 现在会报错了，官方文档看不懂，作者看能否跟进下？

Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information

**Comment by wenyaoliu** [comment]
我也是，没搞懂哪里出问题了

**Comment by 9201314** [comment]
而且我试了另一个主题 stack 没有什么问题

**Comment by wangchucheng** [comment]
应该是因为hugo 0.99.0中引入了新的配置项skipInlineImportsNotFound的原因。eureka被影响是因为使用了inlineImports，将在下一个版本中适配。

**Comment by 9201314** [comment]
> @9201314 @wenyaoliu 你们好，
> 
> 我将Hugo更新至0.99.1后并没有遇到任何问题，可以提供一个有这个问题的示例项目以供修改吗？

我邀请您进入我的博客仓库了

**Comment by ragonneau** [comment]
I believe I have the exact same issue here, as follows.
```
% hugo
Start building sites … 
hugo v0.99.1+extended darwin/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/css/eureka.css_09b9b8e200b8c676e85ddca87a9596ca" not found in file cache
Total in 171 ms
```

Thank you.

**Comment by 9201314** [comment]
v100 又会报错了……作者能否给出什么解决方法，要不然每次升级版本都要来麻烦您

![image](https://user-images.githubusercontent.com/45234281/171304246-05b1f765-e064-4684-97a8-7854f817a4a5.png)

Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/css/eureka.css_59122205213644db2a335025f85b41bf" not found in file cache

**Comment by wangchucheng** [comment]
@9201314 是的，将会针对Hugo 0.100重新生成资源文件。根据[Hugo  Issue 9787](https://github.com/gohugoio/hugo/issues/9787#issuecomment-1139695806)中的描述，0.99和0.100的改动属于Hugo既定的变化，之后版本中将保持稳定。

Eureka作为Hugo的主题无法预测Hugo将要进行的改动，只能在发生改动后进行适配。

**Comment by 9201314** [comment]
好的，感谢作者🙏

**Comment by WindowsXp-Beta** [comment]
My hugo version is `hugo v0.102.3+extended darwin/amd64 BuildDate=unknown` and my eureka is v0.9.3 but I still get the error when running `hugo server -D`
```
Start building sites … 
hugo v0.102.3+extended darwin/amd64 BuildDate=unknown
Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/css/eureka.css_9db11e49eb9eda60f643f6915ca49b2d" not found in file cache
Built in 107 ms
```

**Comment by zohansyahfatomi** [comment]
same here, is there any help?
