### ISSUE TITLE
`shortcode` Availability?

### ISSUE THREAD

**Issue by lennyleadership** [wangchucheng/hugo-eureka#196]
I am using the `hugo-book` theme for a blog project and like the `shortcode` feature.  I wish you could consider it for your next version.

**Comment by wangchucheng** [comment]
`shortcode` is a feature in Hugo. So if you want to develop one then you can use it. 

For Eureka, it does not come with any default shortcode and even if it has, it may not be the same as other theme's shortcodes as those shortcodes are also developed by themselves.
