### ISSUE TITLE
 Cannot find module 'postcss'

### ISSUE THREAD

**Issue by choicky** [wangchucheng/hugo-eureka#2]
目前的版本，按照 `readme` 安装之后，运营时会提示 ：
```
Error: Cannot find module 'postcss'
```

手工运行 `npm install postcss` 后能解决。

BTW，依赖 npm 的话， hugo 就没办法独立运行了，感觉不够方便啊。

**Comment by wangchucheng** [comment]
@choicky 在执行了
```
npm install -g postcss-cli
npm install -g autoprefixer
npm install
```
这三条指令的话应该可以正常运行。需要注意的是`npm install`需要在`eureka`文件夹内执行。

依赖npm确实是目前的一个问题，按照Hugo官方处理`PostCSS`的方式暂时还没有解决方法。我目前在考虑在主题中保存生成后的css，但因为这不是官方支持的方式，我还在寻找最适合的实现，将在未来的release中进行实现。

**Comment by wangchucheng** [comment]
@choicky 更新：在最新的v0.1.1版本中，用户可以不依赖`npm`运行Eureka。目前提供git submodule与hugo modules两种安装方式
