### ISSUE TITLE
"POSTCSS: failed to transform" error on Hugo 0.100.2

### ISSUE THREAD

**Issue by verlanmar** [wangchucheng/hugo-eureka#200]
Hello,

I'm using Hugo 0.100.2 and I'm getting the following error:

> 15:18:29.084	Executing user command: hugo
15:18:29.182	Start building sites … 
15:18:29.182	hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended linux/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio
15:18:29.352	Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/css/eureka.css_59122205213644db2a335025f85b41bf" not found in file cache

I tried setting baseURL as:

> baseURL: /

and as:

> baseURL: https://XXXX.com

and as:

> baseURL: https://XXXX.com/

But nothing worked.

**Comment by wangchucheng** [comment]
Hi @verlanmar,

What is your eureka version? You can upgrade to Eureka 0.9.3 and this should be solved.

**Comment by wangchucheng** [comment]
I can not reproduce this issue with Hugo 0.100.2 and Eureka 0.9.3. Do you want to share your repo so maybe we can have a look at it?

**Comment by verlanmar** [comment]
I tried now doing everything from scratch, and everything is fine now.

https://github.com/verlanmar/-hugo-eureka-test

Not sure why I could not make it work before.

Sorry for the trouble!

**Comment by Fatalerr** [comment]
I got same issue after I upgrade hugo to v0.101.0 and eureka to v0.9.3. but there is no issue if create a new site.
