### ISSUE TITLE
Module Does not Exist

### ISSUE THREAD

**Issue by brimwats** [wangchucheng/hugo-eureka#202]
I updated by both downloading the repository and doing git submodule update

I now get

`Error: module "wangchucheng.com/hugo-marble/utils" not found; either add it as a Hugo Module or store it in "...\\themes".: module does not exist`

**Comment by wangchucheng** [comment]
This is because you use the latest commit in main branch which needs extra config. You should use one of the releases (e.g. v0.9.3) instead for stable use.

**Comment by brimwats** [comment]
thanks!
