### ISSUE TITLE
experiences archetypes file out of date

### ISSUE THREAD

**Issue by bdillahu** [wangchucheng/hugo-eureka#207]
**Describe the bug**

The "experiences" archetype file has:

handler: experiences

which generates a WARN message that it is be deprecated and should be

handler: experience

(no s)

**To Reproduce**

Does this issue reproduce with the latest release?

Using the recommended v0.9.3

1. Add widget file

hugo new -k widgets/experiences homepage/filename.md

2. hugo server -D

**Comment by wangchucheng** [comment]
You can just the handler name from `experiences` to `experience` and you'll be all set.

**Comment by wangchucheng** [comment]
Actually, this warning is generated by Eureka not Hugo. This warning is a reminder for users to update their project before Eureka v1.0

**Comment by bdillahu** [comment]
I'm sorry, I think I've confused things... My suggestion was if the the value should be singular, then we should update this archetype in conjunction, just so people have it "right" when they upgrade.

Regardless, great theme, I'm enjoying it!

**Comment by wangchucheng** [comment]
Oh my bad, I misunderstood it and I would update the corresponding archetype file, thanks ;-)
