### ISSUE TITLE
一旦更改baseURL配置运行hugo就会失败

### ISSUE THREAD

**Issue by waynerv** [wangchucheng/hugo-eureka#21]
如题，保持baseURL配置为默认值“/"时，运行`hugo`以及`hugo server`结果正常。

一旦修改baseURL为其他值（比如我自己的GitHub Pages域名），运行`hugo`会报以下错误：
```
Start building sites … 
Total in 43 ms
Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/waynerv.github.io/css/eureka.css_fc3f76d7bee2760c3a903059afc3d9b2" not found in file cache
```

测试了用git submodule和hugo modules两种方式安装主题，结果都是一样的。hugo版本信息如下：
```
Hugo Static Site Generator v0.79.1/extended darwin/amd64 BuildDate: unknown
```

是我的使用方式不对吗？

**Comment by wangchucheng** [comment]
@waynerv baseURL中需要指明协议（例如https），只输入网址就会产生该报错

**Comment by waynerv** [comment]
baseURL = "https://waynerv.github.io/hugo-blog/"

这是我使用的域名，也存在上述问题。

**Comment by wangchucheng** [comment]
> baseURL = "https://waynerv.github.io/hugo-blog/"
> 
> 这是我使用的域名，也存在上述问题。

经过测试，应该是Hugo没有对baseURL中的路径名(/hugo-blog)进行特殊处理，所以会导致从错误的路径寻找css缓存。Eureka使用了postcss构建css文件，但为了用户使用的方便及生成速度对生成结果进行了缓存。

由于这是一个Hugo的设定，作为主题没有办法干涉。但有两个可以解决该问题的间接方法：

1. 将Eureka中的`resources`文件夹复制到项目根目录下，并将路径由`resources/_gen/assets/css/css/...`改为`resources/_gen/assets/css/<baseURL-subdomain>/css/...`。在你的情况中`baseURL-subdomain`为`hugo-blog`。
2. 在eureka中安装如下依赖：`npm install -g postcss postcss-cli`，`npm install -g autoprefixer`，`npm install`。同时注释掉config.toml文件中的`useResourceCacheWhen = "always"`。这样会使Hugo每次构建时重新生成相关文件。

方法一的好处是不用安装npm依赖且网站生成速度较快（因为不用重新生成css等文件），缺点是用户需要关注Eureka的resources的更新，并移动至自己的项目中。方法二与方法一相反，不需要用户关注resources更新，但需要安装相应的包及生成速度较慢。

关于这个问题我已在Hugo的论坛中提出：https://discourse.gohugo.io/t/cached-resources-not-found-in-file-cache-when-baseurl-contains-subdomain/30182

如果Hugo进行了修复或有从主题角度能彻底解决该问题的方法，我会第一时间进行适配，祝好！

**Comment by waynerv** [comment]
感谢！

**Comment by sswangifly** [comment]
现在这个问题貌似还没有修复，hugo有修复的计划吗？

**Comment by Zacrous** [comment]
感谢！
