### ISSUE TITLE
博客在微信中打开时样式大量丢失

### ISSUE THREAD

**Issue by francisafu** [wangchucheng/hugo-eureka#212]
**Describe the bug**

When open blog with Eureka Theme in WeChat Browser, most of the styles are missed.

**To Reproduce**

Does this issue reproduce with the latest release?

1. Open the blog in browser
2. Share link to WeChat
3. Switch to WeChat andf open the link

**Expected behavior**

Styles stay excatly like what I saw in browser

**Environment**

 - Hugo Version: Latest
 - Eureka Version: Latest
 - Android

**Comment by wangchucheng** [comment]
Websites using Eureka can be opened normally in iOS Wechat. I personally do not have an Android device so I can not reproduce it. Eureka uses tailwind css which requires a “modern” browser to support some new CSS features (e.g. ie is not supported) and it should display normally in every supported browser. One possible cause may be the browser kernel Android Wechat used and this is out of our control.
