### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by RenaudDev** [wangchucheng/hugo-eureka#214]
**Describe the bug**

Hi. I followed all the steps outlined here:
https://www.wangchucheng.com/en/docs/hugo-eureka/getting-started/

and installed using submodule.

When I type `hugo`

I get this

```
Start building sites … 
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1 windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
WARN 2022/10/11 09:53:24 Param 'hero' in params.toml is deprecated and will be removed in Eureka v1.0.0. See https://www.wangchucheng.com/en/docs/hugo-eureka/homepage-configuration/
Error: Error building site: POSTCSS: failed to transform "css/eureka.css" (text/css): resource "css/css/eureka.css_e15155940383ab15df770a6225032646" not found in file cache
Total in 793 ms
```

**To Reproduce**

Does this issue reproduce with the latest release?
I use version v.0.9.3

1. Go through installation process via submodule..

**Expected behavior**

A built website

**Screenshots**

**Environment**

 - Hugo Version: 0.99.1
 - Eureka Version: v0.9.3
 - Go Version: 1.19.2
**Additional context**

**Comment by wangchucheng** [comment]
Hi @RenaudDev,

I think it is because of Hugo Version. Hugo introduces a new feature which makes the cache incompatible with previous version. So you can upgrade to Hugo v100.0+ and this issue should be solved.
