### ISSUE TITLE
Dark mode not working on Tech Mansion site

### ISSUE THREAD

**Issue by hiensarahly** [wangchucheng/hugo-eureka#23]
Hi, I’m loving the Eureka theme — it’s elegant and a light, pleasant experience to read!

I wanted to try out the dark mode on https://www.wangchucheng.com/en/ but it seems not to be working.

Can you please have a look?

**Comment by wangchucheng** [comment]
Hi,

I just tested it in my cell phone. It works all right in my case. If there is anything I can help you, feel free to tell me!


________________________________
发件人: H Ly <notifications@github.com>
发送时间: Monday, December 28, 2020 10:07:36 AM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] Dark mode not working on Tech Mansion site (#23)


Hi, I’m loving the Eureka theme ― it’s elegant and a light, pleasant experience to read!

I wanted to try out the dark mode on https://www.wangchucheng.com/en/ but it seems not to be working.

Can you please have a look?

―

**Comment by hiensarahly** [comment]
I tested it on an ipad & iphone. Pressing dark few times but the color does not change. I’ve taken a screenshot here for your reference:

[![0-C6841-E0-FEC2-498-E-98-B0-0-AFB20-E31-D44.png](https://i.postimg.cc/VLxRK96S/0-C6841-E0-FEC2-498-E-98-B0-0-AFB20-E31-D44.png)](https://postimg.cc/D8cLZX1F)

**Comment by wangchucheng** [comment]
Hi,

I just tested the dark mode in four devices(including iPhone, iPad and desktop) in two places. They all work well.

Have you ever refresh it or something like that? Maybe it is a cache problem. Based on my current testing, I think this may not be a common problem.

**Comment by hiensarahly** [comment]
ah I see it now! Thank you! 😇

**Comment by hiensarahly** [comment]
Updating the OS helped. It looks perfect.

[![A05-AD7-FD-878-B-49-D5-BDE0-FBE973-A6777-A.png](https://i.postimg.cc/L88JZTrd/A05-AD7-FD-878-B-49-D5-BDE0-FBE973-A6777-A.png)](https://postimg.cc/GH6LWkLz)
