### ISSUE TITLE
mermaid.js support for diagrams

### ISSUE THREAD

**Issue by dharmjit** [wangchucheng/hugo-eureka#26]
Will there be mermaid support https://mermaid-js.github.io to render diagrams

**Comment by wangchucheng** [comment]
Yes, I think it is necessary to add a diagram support.


________________________________
发件人: Dharmjit Singh <notifications@github.com>
发送时间: Thursday, December 31, 2020 12:14:12 AM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] mermaid.js support for diagrams (#26)


Will there be mermaid support https://mermaid-js.github.io to render diagrams

―
