### ISSUE TITLE
Heading level 2 not working

### ISSUE THREAD

**Issue by natasak** [wangchucheng/hugo-eureka#27]
Could you please check why Heading 2 is not working? Thank you.

In _index.md I have:

```
+++
title = ...
description = ...
date = ...
series = ...
categories = ...
draft = false
collapsible = true
+++

...

## Header 2
....
```

Preview works, but the commit fails with pipeline error:

`
Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: products/list.html:2:3: executing "main" at <partial "doc_layout.html" .>: error calling partial: "/builds/.../layouts/partials/doc_layout.html:44:23": execute of template failed: template: partials/doc_layout.html:44:23: executing "partials/doc_layout.html" at <partial "doc_toc.html" .>: error calling partial: partial "doc_toc.html" not found
`

**Comment by wangchucheng** [comment]
What is your Eureka version? And sharing a repo which can show this problem may be helpful.


________________________________
发件人: Natasa <notifications@github.com>
发送时间: Tuesday, January 5, 2021 3:18:48 AM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] Heading level 2 not working (#27)


In _index.md I have:

+++
title = ...
description = ...
date = ...
series = ...
categories = ...
draft = false
collapsible = true
+++

...

## Header 2
....


Preview works, but the commit fails with pipeline error:

Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: products/list.html:2:3: executing "main" at <partial "doc_layout.html" .>: error calling partial: "/builds/.../layouts/partials/doc_layout.html:44:23": execute of template failed: template: partials/doc_layout.html:44:23: executing "partials/doc_layout.html" at <partial "doc_toc.html" .>: error calling partial: partial "doc_toc.html" not found

―

**Comment by natasak** [comment]
Hi, it was really a problem with not updated Eureka version. I've updated to the latest master and now it works. Thanks!
