### ISSUE TITLE
关于"阅读更多"链接

### ISSUE THREAD

**Issue by hby07** [wangchucheng/hugo-eureka#28]
主页上的"阅读更多"指向的是当前主页,相当于没做跳转.
这里能否改成可配置的呢?

**Comment by wangchucheng** [comment]
感谢你的提醒，这应该是一个bug，将会在这两天进行修改。设计中阅读更多会跳到该类别的section页。


________________________________
发件人: 白日呓语 <notifications@github.com>
发送时间: Thursday, January 7, 2021 5:45:07 PM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] 关于"阅读更多"链接 (#28)


主页上的"阅读更多"指向的是当前主页,相当于没做跳转.

―

**Comment by hby07** [comment]
很喜欢这个模板,希望会越来越好!加油
