### ISSUE TITLE
主页配置

### ISSUE THREAD

**Issue by keets2012** [wangchucheng/hugo-eureka#29]
![image](https://user-images.githubusercontent.com/13324388/104092772-26ea7f00-52c1-11eb-9bf1-2897ae0ae21a.png)

请问主页如何配置成你示例的样子，方便的话，加个wx请教下，感谢。 aoho2012

**Comment by wangchucheng** [comment]
请参考exampleSite中的homepage并查看文档即可成功配置主页。exampleSite中的主页可以正常渲染。截图中可能的原因是没有指定handler或其他问题。

**Comment by keets2012** [comment]
handler好像没有文档介绍，要不加一下联系方式？谢谢🙏------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;C.&amp;nbsp;Wang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月9日(星期六) 晚上10:42
收件人:&nbsp;&quot;wangchucheng/hugo-eureka&quot;<hugo-eureka@noreply.github.com&gt;;
抄送:&nbsp;&quot;kidme&quot;<928420597@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangchucheng/hugo-eureka] 主页配置 (#29)

**Comment by wangchucheng** [comment]
handler的文档位于https://www.wangchucheng.com/zh/docs/eureka/homepage-configuration/#%E9%85%8D%E7%BD%AE%E5%B0%8F%E7%BB%84%E4%BB%B6。该属性的可选值为前文中提到的pages，about，vintage，blank。

由于个人原因可能无法提供微信，你可以通过issue或其他公开的联系方式联系我，祝好！

**Comment by keets2012** [comment]
![image](https://user-images.githubusercontent.com/13324388/104114663-e2eb8e80-5341-11eb-9432-e69e43e36e90.png)
感谢，但是文档并没有示例怎么用，如上图，主页和关于还是空白的，能给个配置的例子吗，配置成你给的效果图。

**Comment by wangchucheng** [comment]
配置的例子在exampleSite/content/homepage中，这是示例网站的地址


________________________________
发件人: kidme <notifications@github.com>
发送时间: Sunday, January 10, 2021 12:48:03 PM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: C. Wang <wangchucheng@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [wangchucheng/hugo-eureka] 主页配置 (#29)


[image]<https://user-images.githubusercontent.com/13324388/104114663-e2eb8e80-5341-11eb-9432-e69e43e36e90.png>
感谢，但是文档并没有示例怎么用，如上图，主页和关于还是空白的，能给个配置的例子吗，配置成你给的效果图。

―
