### ISSUE TITLE
关于中文语言设置下「文章」标题显示的问题

### ISSUE THREAD

**Issue by hishark** [wangchucheng/hugo-eureka#3]
你好，我将博客语言改成中文 zh 之后，其他地方都为中文，但是只有此处为 Posts。
![image](https://user-images.githubusercontent.com/29684201/97140131-f18cc580-1796-11eb-9e76-ebf2a4fd10eb.png)

尝试在 `i18n/zh.toml` 找了一下也没有可以设置的地方，请问在哪可以改成中文哦？
![image](https://user-images.githubusercontent.com/29684201/97140080-dc179b80-1796-11eb-99e6-5a5398a3c3a8.png)

看作者的网站在「简体中文」版本下是正常显示「文章」的。
![image](https://user-images.githubusercontent.com/29684201/97139991-b68a9200-1796-11eb-889a-807383a68a0c.png)

**Comment by wangchucheng** [comment]
@hishark 这是一个Hugo的设置问题，你只需在`posts`文件夹下新建`_index.md`并指定`title`属性为你需要的值即可。更多相关内容可参考Hugo官方文档的[Page Bundles](https://gohugo.io/content-management/page-bundles/)。祝好！

**Comment by hishark** [comment]
> @hishark 这是一个Hugo的设置问题，你只需在`posts`文件夹下新建`_index.md`并指定Front Matter中`title`属性为你需要的值即可。更多相关内容可参考Hugo官方文档的[Page Bundles](https://gohugo.io/content-management/page-bundles/)。祝好！

哈哈好的，昨天刚开始用 hugo 不太清楚，谢谢啦！
