### ISSUE TITLE
Add badge for theme Eureka

### ISSUE THREAD

**Issue by PanZiwei** [wangchucheng/hugo-eureka#36]
**Is your feature request related to a problem? Please describe.**

Add a badge for theme Eureka to README.md.

**Describe the solution you'd like**

I generate a badge here: https://img.shields.io/badge/Theme-Eureka-%23de8800

The badge color is from the picture in the vintage widget in the Eureka theme.

**Additional context**

Badge example:

[![Theme is Eureka](https://img.shields.io/badge/Theme-Eureka-%23de8800)](https://github.com/wangchucheng/hugo-eureka)

Code:
```
[![Theme is Eureka](https://img.shields.io/badge/Theme-Eureka-%23de8800)](https://github.com/wangchucheng/hugo-eureka)
```

**Comment by wangchucheng** [comment]
Great! I will see what else can be added also.

**Comment by PanZiwei** [comment]
This one may be helpful:
[![Generator is Hugo](https://img.shields.io/badge/Generator-Hugo-ff4088?&logo=hugo)](https://github.com/gohugoio/hugo)
Code:
```
[![Generator is Hugo](https://img.shields.io/badge/Generator-Hugo-ff4088?&logo=hugo)](https://github.com/gohugoio/hugo)
```
