### ISSUE TITLE
关于 toc 的两个小建议

### ISSUE THREAD

**Issue by choicky** [wangchucheng/hugo-eureka#4]
v.11 版消除了对 npm 的依赖，👍。越来越接近我想要的效果了 

关于 toc ，我提供两个小建议。

1. v.11 版，本地测试存在如下问题：不管是否在 `config` 文件增加 `toc = true` ，页面都不显示目录；只有在具体的 post 里面加入`toc =true` 。建议将相关的配置放到 `config.toml` 里面

2. 我的 hugo 的一个作用是用来转载法律全文，因此会存在多级、多行的 toc 。目前的 toc 没有自动缩叠功能，会导致页面右侧完全被 toc 占满，且鼠标滚动还无法滚动 toc。 例如， 如果使用本模板， [专利法](https://itlaws.cn/posts/patent-law-2020/ )就很难点击到第四十条；如遇到 [民法典](https://itlaws.cn/posts/civil-code-2020/) 这种目录行数更多的，则更难了。

**Comment by wangchucheng** [comment]
@choicky 针对第一条建议，在未来的版本中`toc`默认值可能会改为`true`。没在config进行配置的原因是许多用户需要针对某篇文章选择是否使用目录。针对第二条建议我会在未来收集更多的反馈后进行进一步的完善。感谢对Eureka主题的建议及关心！

**Comment by choicky** [comment]
第一个建议应该比较好解决，在 `config.toml` 增加 `toc = false` 就好。这样，只是临时针对某篇 post 启用 toc 时，在该 post 设定 `toc = true ` 来覆盖即可；而针对我这样的用户，就是直接将 `config.toml` 的 `toc = false` 改为 `toc = true`

**Comment by wangchucheng** [comment]
> 第一个建议应该比较好解决，在 `config.toml` 增加 `toc = false` 就好。这样，只是临时针对某篇 post 启用 toc 时，在该 post 设定 `toc = true ` 来覆盖即可；而针对我这样的用户，就是直接将 `config.toml` 的 `toc = false` 改为 `toc = true`

是的。感谢相关建议，将在未来版本中不断改善Eureka。
