### ISSUE TITLE
主页配置问题/功能建议

### ISSUE THREAD

**Issue by PanZiwei** [wangchucheng/hugo-eureka#40]
你好，
感谢开发这么简洁漂亮的模板。关于主页配置/功能建议，有几个问题想要请教/交流：

1. 菜单栏能否添加分类(category)或者标签(tags)一栏？
效果举例：
https://themes.gohugo.io//theme/hugo-theme-meme/categories/
https://hugoloveit.com/categories/
https://themes.gohugo.io//theme/hugo-theme-meme/tags/
https://hugoloveit.com/tags/ 

2. 如何在日志中自动生成如下目录？需要在Configure.toml中配置还是要在`post/_index.md`中添加呢？具体怎么操作？
以你的博文举例：https://www.wangchucheng.com/zh/posts/migration-from-nginx-to-envoy/

3. 日志展示时能否仅显示摘要部分（而不是显示前XX字）？目前日志显示的是创作时间，阅读时长和分类，怎么添加其他属性呢（比如最后修改时间）？

4. 我在`archetypes/default.md`设置了如下默认参数。
使用`hugo new post.md`时会自动填充`date`和`lastmod`为同一时间，如果我后续修改日志，如何自动更新`lastmod`？
```
+++
title = "{{ replace .Name "-" " " | title }}"
date = "{{ .Date }}"
lastmod = "{{ .Date }}"
categories = [ ]
tags = [ ]
slug = ""
draft = false
+++
```

5. 是否考虑支持Waline评论系统/Valine评论系统/utterances（基于 GitHub Issues 的评论系统）？
Waline官网：https://waline.js.org/
Valine官网：https://valine.js.org/index.html
utterances: https://github.com/utterance/utterances
别人写的静态博客系统比较：https://eallion.com/comments/

6. 是否考虑添加搜索功能？

7. 添加一个Github issue，以汇总使用该主题的用户及博客链接？

8. 我自己对Hugo主题开发比较感兴趣，请问你是否有推荐的博客/教程？

谢谢解答！

**Comment by wangchucheng** [comment]
对于问题请在[讨论区](https://github.com/wangchucheng/hugo-eureka/discussions)提出，我会对此进行回答。感谢对Eureka的支持，祝好！
