### ISSUE TITLE
关于归档、标签、分类功能

### ISSUE THREAD

**Issue by hishark** [wangchucheng/hugo-eureka#5]
请问作者未来有加入这三个功能的计划吗～

**Comment by hishark** [comment]
目前标签和分类可以在文章内直接点击跳转查看，请问未来是否有添加单独的分类汇总页以及标签汇总页的计划喔 😉

**Comment by wangchucheng** [comment]
@hishark 这同样是一个Hugo的使用问题。这类功能在Hugo中被称为Taxonomies。跳转查看到的页面即为Taxonomies的汇总页。例如在导航栏中添加访问标签页的链接只需设置其值为`/tags/`即可，更多内容可参考Hugo关于Taxonomies的文档。祝好！

**Comment by hishark** [comment]
> @hishark 这同样是一个Hugo的使用问题。这类功能在Hugo中被称为Taxonomies。跳转查看到的页面即为Taxonomies的汇总页。例如在导航栏中添加访问标签页的链接只需设置其值为`/tags/`即可，更多内容可参考Hugo关于Taxonomies的文档。祝好！

啊原来如此！刚使用 Hugo 不太清楚，还以为也是需要自定义页面呢。
我是时候把 Hugo 的文档好好看一遍了哈哈，感谢感谢(^v^)/~

**Comment by hishark** [comment]
不过归档功能是不是 Hugo 默认没有的哦？我 Google 看了看大多数人都是自己动手添加了一个归档页，比如这个：[Hugo添加归档页面](https://www.ariesme.com/posts/2019/add_archive_page_for_hugo/)

**Comment by wangchucheng** [comment]
> 不过归档功能是不是 Hugo 默认没有的哦？我 Google 看了看大多数人都是自己动手添加了一个归档页，比如这两个：[为hugo添加归档页面](https://xbc.me/how-to-create-an-archives-page-with-hugo/)、[Hugo添加归档页面](https://www.ariesme.com/posts/2019/add_archive_page_for_hugo/)

是的，归档页你可以在任意你希望的位置进行添加即可。页面的访问方法可以参照Hugo文档。

**Comment by hishark** [comment]
> > 不过归档功能是不是 Hugo 默认没有的哦？我 Google 看了看大多数人都是自己动手添加了一个归档页，比如这两个：[为hugo添加归档页面](https://xbc.me/how-to-create-an-archives-page-with-hugo/)、[Hugo添加归档页面](https://www.ariesme.com/posts/2019/add_archive_page_for_hugo/)
> 
> 是的，归档页你可以在任意你希望的位置进行添加即可。页面的访问方法可以参照Hugo文档。

嗯嗯好的～谢谢你哈！
