### ISSUE TITLE
Add busuanzi不蒜子 or similar extensions to count visitors

### ISSUE THREAD

**Issue by PanZiwei** [wangchucheng/hugo-eureka#57]
Add busuanzi to count visitors in the footnote or count visits for each blog.

busuanzi website: https://busuanzi.ibruce.info/

Potential solution(Chinese version): https://cloud.tencent.com/developer/article/1669144

**Comment by wangchucheng** [comment]
I’m sorry that we do not have a timetable for this feature for now as we want to improve Eureka in many aspects and the time is limited. But any PR is welcome!


________________________________
发件人: PanZiwei <notifications@github.com>
发送时间: Wednesday, February 3, 2021 1:05:24 PM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] Add busuanzi不蒜子 or similar extensions to count visitors (#57)


Add busuanzi to count visitors in the footnote or count visits for each blog.

busuanzi website: https://busuanzi.ibruce.info/

Potential solution(Chinese version): https://cloud.tencent.com/developer/article/1669144

―
