### ISSUE TITLE
文章末尾作者信息的社交按钮点击无法跳转

### ISSUE THREAD

**Issue by hishark** [wangchucheng/hugo-eureka#6]
抓个虫🐛，点击按钮只是单纯刷新当前页面，没有跳转到对应的社交网站

![image](https://user-images.githubusercontent.com/29684201/97771702-941fbc80-1b7a-11eb-9cfc-fb59ee176420.png)

**Comment by wangchucheng** [comment]
@hishark 是的，感谢你的issue。我也发现了这个bug，最新的commit已经修复了此问题，我今天将发布一个新版本。届时你只需更新到最新版本即可。祝好！

**Comment by wangchucheng** [comment]
@hishark v0.1.2已发布。更新到v0.1.2即可解决该问题。祝好

**Comment by hishark** [comment]
> @hishark 是的，感谢你的issue。我也发现了这个bug，最新的commit已经修复了此问题，我今天将发布一个新版本。届时你只需更新到最新版本即可。祝好！

好的～辛苦啦😆
