### ISSUE TITLE
向 Google Search Console 添加网址前缀时，无法通过 Google Analytics（分析）的方式验证所有权

### ISSUE THREAD

**Issue by xuchunqiu** [wangchucheng/hugo-eureka#7]
## 目的
希望 Google 收录我的博客

### 环境
Hugo v0.78.1
Eureka v0.1.3

### 博客配置过程
1. 按照教程的 [入门](https://www.wangchucheng.com/zh/docs/eureka/content-management/) 章节通过 Hugo Modules 安装了 Eureka 主题
2. 按照教程的 [内容管理](https://www.wangchucheng.com/zh/docs/eureka/content-management/) 章节添加了 [两篇中文文章](https://xuchunqiu.github.io/zh/posts/)
3. 按照教程的 [定制Eureka](https://www.wangchucheng.com/zh/docs/eureka/customize-eureka/) 和 [多语言模式](https://www.wangchucheng.com/zh/docs/eureka/multilingual-mode/) 章节启用了多语言模式
4. 按照教程的 [定制Eureka](https://www.wangchucheng.com/zh/docs/eureka/customize-eureka/) 章节在 `config/_default/config.toml` 中填入了我自己的 Google Analytics 代码（衡量 ID）
5. 将站点原始文件存入私有仓库 A，将每次的 commit 通过 [Hugo to GH Pages](https://github.com/marketplace/actions/hugo-to-gh-pages) 生成静态网站部署到私有仓库 `xuchunqiu/xuchunqiu.github.io`

### Google Search Console 提交过程
1. 进入其 [欢迎页面](https://search.google.com/search-console/welcome)，提交网址前缀 https://xuchunqiu.github.io 或是 https://xuchunqiu.github.io/zh/
2. 弹出验证所有权的对话框，可选的验证方式如下：
![image](https://user-images.githubusercontent.com/57806510/98936567-18c9ed80-2520-11eb-99aa-44519fb48755.png)
3. 点开 Google Analytics 项，其要求如下：
![image](https://user-images.githubusercontent.com/57806510/98936711-4adb4f80-2520-11eb-93a6-47e17712bda2.png)
4. 在我的首页上使用 Chrome 的 DevTools 检查，发现上述条件1不满足，条件2、3满足：
![image](https://user-images.githubusercontent.com/57806510/98937373-4499a300-2521-11eb-811a-eb6f2a984c6a.png)与你的博客相同：
![image](https://user-images.githubusercontent.com/57806510/98937653-ad811b00-2521-11eb-944f-af5291d0ed45.png)
5. 点击验证按钮，等待片刻后，出现所有权验证失败的提示：![image](https://user-images.githubusercontent.com/57806510/98934233-b91e1300-251c-11eb-83b2-d19299927447.png)

## 我想请教
我注意到在 Google 中是可以检索出”技术公馆“的，同时 Chrome 扩展 Tag Assistant (by Google) 显示我俩的 Result of Tag Analysis 并不相同：
![image](https://user-images.githubusercontent.com/57806510/98939252-18cbec80-2524-11eb-8551-4bff3f081dc1.png)
![image](https://user-images.githubusercontent.com/57806510/98939310-339e6100-2524-11eb-88d3-0479f09593ca.png)
所以想请问，为了以 Google Analytics（分析）的方式通过 Google Search Console 的所有权验证，我还要对哪些地方进行配置呢？还是说我只能以其它方式（如 HTML 标记）进行所有权验证？

**Comment by wangchucheng** [comment]
@xuchunqiu 我们的Result of Tag Analysis不同的原因应该是因为我关联了旧版的Universal Analytics（UA开头的编号），而你只使用了新版的ga4（G开头的编号）。引入Google Analytics的相关代码我使用的是Google提供的代码，应该不会是代码的相关问题。我的猜测是因为ga4目前处在测试阶段，许多功能并不完善，Google Search Console可能只能验证旧版的Universal Analytics，因此导致的此问题。祝好！

**Comment by xuchunqiu** [comment]
感谢回复！我尝试通过 HTML 标记的形式进行验证，很快就通过了。
