### ISSUE TITLE
Theme not Rendering on Github

### ISSUE THREAD

**Issue by Steve-Shao** [wangchucheng/hugo-eureka#72]
I was building a site using the Eureka Theme. It worked fine locally but when I pushed it to my Github repo, the theme was not rendering. 

I checked my baseURL and it was correct. I tried using other themes and the page rendered. 

Can you help me with identifying the issue? 

Thank You!

**Comment by Steve-Shao** [comment]
Also, when I try to use a baseURL like "https://mysite.com/main", the site cannot be rendered. There has to be nothing after the slash "/". Is there a quick fix to it? 

Thanks.

**Comment by Steve-Shao** [comment]
I've identified the problem -- I deleted the repo completely, created a new repo, and it worked. It seems like a problem with Github on the backend -- something was not cleaned up until I remove the repo. 

Many apologizes for the inconvenience. 

The subdir issue in baseURL is still a problem though.

**Comment by snowgears** [comment]
@Steve-Shao what was the fix for this? I am running into an issue where my hugo site is totally fine when I am running it on my local server but the theme and everything is totally broken when I push the public folder (where the static files generated) to github pages. Any help you could provide here would be awesome

**Comment by Steve-Shao** [comment]
> @Steve-Shao what was the fix for this? I am running into an issue where my hugo site is totally fine when I am running it on my local server but the theme and everything is totally broken when I push the public folder (where the static files generated) to github pages. Any help you could provide here would be awesome

One thing to check is that the "baseURL" in your config file needs to match the URL of your github repo.
