### ISSUE TITLE
针对最新版hugo 0.81建议更新函数

### ISSUE THREAD

**Issue by unixetc** [wangchucheng/hugo-eureka#73]
详情见下图 

提示`Page.GetParam is deprecated and will be removed in a future release. Use .Param or .Params.myParam.`

![微信截图_20210228125121.png](https://i.loli.net/2021/02/28/VB9qPFCaT8Nsitu.png)

**Comment by wangchucheng** [comment]
感谢提示，将在近期进行更新。


________________________________
发件人: alair <notifications@github.com>
发送时间: Sunday, February 28, 2021 12:54:45 PM
收件人: wangchucheng/hugo-eureka <hugo-eureka@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [wangchucheng/hugo-eureka] 针对最新版hugo 0.81建议更新函数 (#73)


详情见下图

提示Page.GetParam is deprecated and will be removed in a future release. Use .Param or .Params.myParam.

[微信截图_20210228125121.png]<https://camo.githubusercontent.com/4a04b6147946088296f2b79cebd864ff4aed8f69b1f77538f1f0c389b64213cf/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30322f32382f564239715046436154384e736974752e706e67>

―
