### ISSUE TITLE
Is there any plan to upgrade tailwind css to 2.0?

### ISSUE THREAD

**Issue by gurumark** [wangchucheng/hugo-eureka#78]
Hello,
Is there any plan to upgrade tailwind CSS to 2.0?
Thank you.

**Comment by wangchucheng** [comment]
I hope to upgrade it in the next minor version.


________________________________
发件人: gurumark ***@***.***>
发送时间: Saturday, March 20, 2021 8:28:44 PM
收件人: wangchucheng/hugo-eureka ***@***.***>
抄送: Subscribed ***@***.***>
主题: [wangchucheng/hugo-eureka] Is there any plan to upgrade tailwind css to 2.0? (#78)


Hello,
Is there any plan to upgrade tailwind CSS to 2.0?
Thank you.

―
