### ISSUE TITLE
Default theme style (dark/light)

### ISSUE THREAD

**Issue by ScriptFanix** [wangchucheng/hugo-eureka#8]
Hello

It would be ghreat to be able to set the default theme to dark instead of light.

**Comment by wangchucheng** [comment]
Hi,

Thank you for your suggestion, I think this is a feature worth adding. It will be added in a future release!

**Comment by wangchucheng** [comment]
@ScriptFanix This feature has been implemented in 1fc544b.

Now you can set `colorScheme` in `params.toml` to customize it. You can checkout master to preview it or wait for the next release which may be released in 3-5 days. Thank you for your suggestion to Eureka!
