### ISSUE TITLE
Will Mathjax or Katex will supported in future?

### ISSUE THREAD

**Issue by stO-Orz** [wangchucheng/hugo-eureka#9]
Privately speaking, this is the most beautiful Hugo theme I have seen.

My content will contains a lot of mathematical formulas, will Mathjax or Katex be supported by Eureka in future? :)

**Comment by wangchucheng** [comment]
@stO-Orz Thank you for your appreciation of Eureka.

In the future I will support one of these two (maybe both?😝) features. I think this will not take long.

**Comment by stO-Orz** [comment]
> @stO-Orz Thank you for your appreciation of Eureka.
> 
> In the future I will support one of these two (maybe both?😝) features. I think this will not take long.

Thanks~ Look forward to that 👍

**Comment by wangchucheng** [comment]
@stO-Orz  This feature has been implemented in b346260.

Now you can use katex in Eureka. You can checkout master to preview it or wait for the next release which may be released in tomorrow.

Thank you for your suggestion to Eureka!
